# Generated by Django 5.2.6 on 2025-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpacalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='grade',
            field=models.CharField(),
        ),
    ]
